defaults:
  - mppi: boxer_push
  - isaacgym: normal

render: true
n_steps: 5
nx: 4

actors: ['boxer', 'block', 'goal']
initial_actor_positions: [[0.0, 0.0, 0.05]]

hydra:
  searchpath:
    - pkg://conf